version: "3.5"

services:
  api01: &api
    hostname: api01
    image:
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
      - ./resources/schema.sql:/app/resources/schema.sql
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "220MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - db
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_DB=carimbo
      - POSTGRES_USER=carimbo-miguel
      - POSTGRES_PASSWORD=xerox
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1